[env:esp32_parkinglot]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_protocol = espota
; upload_port = 192.168.1.45
monitor_filters = send_on_enter
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
	adafruit/Adafruit GFX Library @ ^1.11.9